# See https://github.com/binder-examples/conda
name: radis-env
channels:
- conda-forge
- astropy
dependencies:
- python=3.6
- numpy
- scipy
- matplotlib
- pandas
- plotly
- h5py
- numba
- astropy  # Unit aware calculations
- plotly>=2.5.1  # for line survey HTML output
- termcolor  # terminal colors
- configparser
- astroquery>=0.3.9  # to fetch HITRAN databases
- pytest  # to run test suite
- h5py  # to write HDF5 files
- joblib  # for parallel loading of SpecDatabase
- numba  # just-in-time compiler
- pip
# Specific to radis-lab : 
- pyqt
- ipympl
- pip:
  - publib>=0.3.2  # Plotting styles for Matplotlib
  - hitran-api
  - json-tricks>=3.13.6  # to deal with non jsonable formats
  - mpldatacursor
  - tables  # for pandas to HDF5 export
  # Specific to radis-lab:
  - radis>=0.9.26
  - jupyter-offlinenotebook