# See https://github.com/binder-examples/conda
name: radis-env
channels:
- conda-forge
- astropy
- plotly
dependencies:
# Radis dependencies : see https://github.com/radis/radis/blob/master/environment.yml
- python=3.6
- numpy
- scipy
- matplotlib
- pandas>=1.0.5
- plotly
- numba
- astropy  # Unit aware calculations
- plotly>=2.5.1  # for line survey HTML output
- termcolor  # terminal colors
- configparser
- astroquery>=0.3.9  # to fetch HITRAN databases
- pytest  # to run test suite
- joblib  # for parallel loading of SpecDatabase
- numba  # just-in-time compiler
- pip
# Specific to radis-lab : 
- ipympl>=0.5.6  # for interactive plots
- jupyterlab
- ipywidgets>=7.5    # for plotly
- python-kaleido     # for plotly
- pip:
  # Radis dependencies : see https://github.com/radis/radis/blob/master/environment.yml
  - publib>=0.3.2  # Plotting styles for Matplotlib
  - hitran-api
  - json-tricks>=3.13.6  # to deal with non jsonable formats
  - mpldatacursor
  - tables  # for pandas to HDF5 export
  # Specific to radis-lab:
  - radis>=0.9.29
  - jupyter-offlinenotebook
  - jupyterlab_hdf
